-- Disable RLS for administrative tables to allow the mock login system to work
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.briefing_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.fixed_costs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_rejections DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.partner_goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_feedbacks DISABLE ROW LEVEL SECURITY;
